/* data.jsx — mock content for the Kenji prototype */

window.KENJI_DATA = {
  user: {
    name: "Arjun Rao",
    initials: "AR",
    headline: "Full-stack engineer · 6y · ex-Monzo, Stripe",
    location: "Lisbon, PT · open to remote",
  },

  stories: [
    {
      id: "s1",
      kind: "experience",
      title: "Rewrote Monzo's merchant dispute flow",
      org: "Monzo · Sr. Engineer",
      period: "2022 — 2024",
      summary: "Cut avg resolution time from 11 days to 3.4. Designed the evidence-gathering state machine, shipped the customer-facing UI in React Native, wrote the FastAPI service handling 40k disputes/month.",
      tags: ["python", "fastapi", "react-native", "state-machines", "payments"],
    },
    {
      id: "s2",
      kind: "experience",
      title: "Built Stripe's first ML-based fraud feedback loop",
      org: "Stripe · Engineer",
      period: "2020 — 2022",
      summary: "Owned the pipeline that surfaced uncertain fraud decisions to analysts and fed corrections back into training. Moved F1 from 0.78 → 0.86 over 8 months.",
      tags: ["python", "ml-ops", "postgres", "human-in-the-loop"],
    },
    {
      id: "s3",
      kind: "project",
      title: "Kenji (this!) — open-source job agent",
      org: "Side project · 2025",
      summary: "React + FastAPI + Turso. Built agent command center that tailors resumes against ATS filters, ranks jobs using user stories rather than keywords.",
      tags: ["agents", "oss", "turso", "react"],
    },
    {
      id: "s4",
      kind: "preference",
      title: "What I actually want next",
      summary: "Small team (< 30 eng), product-shaped work, something where I talk to users weekly. Prefer infra/AI problems with a human-visible surface. Not interested in pure platform plumbing or pre-PMF consumer.",
      tags: ["small-team", "AI", "product-shaped"],
    },
    {
      id: "s5",
      kind: "trait",
      title: "I think best in writing",
      summary: "I write RFCs before code. I prefer async review. Put me in a company that runs on docs, not standups.",
      tags: ["writing", "async"],
    },
  ],

  jobs: [
    {
      id: "j1",
      company: "Resolute",
      logo: "R",
      logoColor: "oklch(0.72 0.14 180)",
      role: "Founding Engineer, AI Agents",
      location: "Remote (EU)",
      comp: "€120–160k + 0.6–1.2%",
      size: "12 eng",
      posted: "2d",
      match: 94,
      reasoning: "You rebuilt Monzo's dispute flow as an evidence-gathering state machine — that is essentially what Resolute's agent product does for insurance. Small team, doc-driven, async.",
      axes: { skills: 95, trajectory: 92, values: 96, workStyle: 90 },
      source: "LinkedIn",
      whyNot: null,
    },
    {
      id: "j2",
      company: "Paperseed",
      logo: "P",
      logoColor: "oklch(0.65 0.12 45)",
      role: "Staff Engineer, Applied AI",
      location: "Lisbon / Hybrid",
      comp: "€140–175k",
      size: "24 eng",
      posted: "4h",
      match: 89,
      reasoning: "Your Stripe human-in-the-loop pipeline maps directly onto their review tooling. Hybrid in Lisbon, product-shaped work with enterprise design partners.",
      axes: { skills: 92, trajectory: 88, values: 85, workStyle: 91 },
      source: "Company site",
    },
    {
      id: "j3",
      company: "Turnstile",
      logo: "T",
      logoColor: "oklch(0.55 0.14 260)",
      role: "Senior Backend Engineer",
      location: "Remote (global)",
      comp: "$170–210k",
      size: "18 eng",
      posted: "1d",
      match: 82,
      reasoning: "Strong Python/FastAPI fit and they run on RFCs. But the role is infrastructure-heavy; you said you want product-shaped work. Worth a look, not the top.",
      axes: { skills: 94, trajectory: 78, values: 85, workStyle: 72 },
      source: "Wellfound",
    },
    {
      id: "j4",
      company: "Kinfolk",
      logo: "K",
      logoColor: "oklch(0.62 0.13 330)",
      role: "Senior Full-Stack, Trust & Safety",
      location: "Remote (AMER/EU)",
      comp: "$150–190k",
      size: "40 eng",
      posted: "3d",
      match: 78,
      reasoning: "Fraud/ML experience is highly relevant and the team ships weekly. Slightly larger than your preference (40 eng) and uses standups.",
      axes: { skills: 88, trajectory: 82, values: 74, workStyle: 68 },
      source: "LinkedIn",
    },
    {
      id: "j5",
      company: "Halfsheet",
      logo: "H",
      logoColor: "oklch(0.58 0.12 145)",
      role: "Product Engineer",
      location: "Berlin / Hybrid",
      comp: "€110–135k",
      size: "8 eng",
      posted: "6h",
      match: 73,
      reasoning: "Tiny team, async-first, beautiful product. Compensation sits below your last band and they require one week/mo in Berlin.",
      axes: { skills: 78, trajectory: 70, values: 88, workStyle: 62 },
      source: "Hacker News",
    },
    {
      id: "j6",
      company: "Arcline",
      logo: "A",
      logoColor: "oklch(0.55 0.10 25)",
      role: "Backend Engineer, Payments",
      location: "Remote (US only)",
      comp: "$160–200k",
      size: "120 eng",
      posted: "5d",
      match: 54,
      reasoning: "Payments experience fits, but US-only and 120 engineers — both outside what you asked for.",
      axes: { skills: 86, trajectory: 60, values: 40, workStyle: 30 },
      source: "LinkedIn",
    },
  ],

  atsChecks: [
    { label: "Role keywords", score: 96, note: "Matches 12/13 required terms", state: "ok" },
    { label: "Seniority signal", score: 92, note: "Staff/Senior language present in 4 of 5 bullets", state: "ok" },
    { label: "Quantified impact", score: 88, note: "7 metrics across 3 roles", state: "ok" },
    { label: "Format parseability", score: 100, note: "Single column, no tables, embedded fonts", state: "ok" },
    { label: "Keyword density", score: 71, note: "'Agent' appears 1× — job posting uses it 6×", state: "warn" },
    { label: "Tenure pattern", score: 94, note: "No job < 14 months", state: "ok" },
  ],
};
